name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_LINES_OF_CODE: False
          SHOW_PROFILE_VIEWS: False
          SHOW_DAYS_OF_WEEK: False
          SHOW_SHORT_INFO: False
          SHOW_LOC_CHART: False
          SHOW_PROJECTS: False
          SHOW_LANGUAGE_PER_REPO: False
          SECTION_NAME: waka
          SHOW_OS: False
          SHOW_EDITORS: False
          SHOW_TIMEZONE: False
          SHOW_COMMIT: True
          SHOW_LANGUAGE: False
          SHOW_UPDATED_DATE: False
          SHOW_TOTAL_CODE_TIME: False
          COMMIT_BY_ME: False
          COMMIT_SINGLE: False
          LOCALE: en
          SYMBOL_VERSION: 1
